react-design in progress
bbrown949/c0523-code-solutions pull request #6
Opened 2023-06-28 18:03 UTC by bbrown949

![Screenshot 2023-06-28 at 2 00 40 PM](https://github.com/bbrown949/c0523-code-solutions/assets/117103446/8c52d650-ce13-452a-abcd-5d13f2675ab8)

2023-06-28 18:38 UTC, TimelikeClosure requested changes

2023-06-28 18:38 UTC, TimelikeClosure commented on react-design/my-app/src/Buttons.js
> +}
I suggest renaming this component: `Buttons` implies this component contains a list of buttons, not exactly one button, which can be misleading and make it harder to debug later.

2023-06-28 18:38 UTC, TimelikeClosure commented on react-design/my-app/src/ButtonClick.js
> +export default function ButtonClick() {}
To avoid confusion, try not to capitalize your functions unless they're meant to be components

2023-06-29 16:03 UTC, bbrown949 commented
https://github.com/bbrown949/c0523-code-solutions/assets/117103446/3c3c925d-9c3a-44e2-87e5-9ecfd40df7f4

2023-06-29 16:24 UTC, TimelikeClosure approved these changes

2023-07-06 15:36 UTC, merged